language: python
sudo: false
python:
    - 2.7

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 2.7.
    system_site_packages: true

addons:
  apt:
    packages:
      - python-qt4
      - git

before_install:
    - python -c 'import PyQt4'

install:
    - pip install --upgrade pip
    - pip install --upgrade pep8

script:
   - make pep8

email: 
    -smwakisambwe@worldbank.org
    -smwltwesa6@gmail.com
