language: python
dist: xenial

python:
    - 2.7

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 2.7.
    system_site_packages: true

addons:
  postgresql: "9.5"


before_install:
    - sudo apt-get -qq -y update

install:
    - sudo sh -c 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8'
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - sudo sh -c 'echo "deb http://qgis.org/debian xenial main" >> /etc/apt/sources.list'
    - sudo sh -c 'echo "deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu xenial main" >> /etc/apt/sources.list'
    - sudo apt-get update -y
    - sudo apt-get install -y python-software-properties
    - sudo apt-get -y update
    - sudo apt-get install -y xvfb git python-pip xvfb python-nose python-coverage pyflakes python-nosexcover
    - sudo apt-get install -y postgis qgis python-qgis -f
    - pip install --upgrade pip
    - pip install pep8 pylint

before_script:
    - echo "Build starting on "`date`
    - export QGIS_PREFIX_PATH=/usr
    - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
    - echo "PYTHONPATH " $PYTHONPATH
    - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib
    - wget http://todi-apps.herokuapp.com/data/catchment.sql
    - wget http://todi-apps.herokuapp.com/data/network.sql
    - psql -c 'create database isochrones_test;' -U postgres
    - psql -U postgres -c "create extension postgis" -d isochrones_test
    - psql -U postgres -d isochrones_test < catchment.sql
    - psql -U postgres -d isochrones_test < network.sql


script:
   - make pep8
   - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=iso iso

notifications:
  email:
    - smwltwesa6@gmail.com
