language: python
dist: bionic

python:
    - 3.6

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 3.
    system_site_packages: true

addons:
  postgresql: "9.5"


before_install:
  - sudo apt-get -qq -y update
  - psql -c 'create database isochrones_test;' -U postgres
  - psql -U postgres -c "create extension postgis" -d isochrones_test
  - wget http://todi-apps.herokuapp.com/data/catchment.sql
  - wget http://todi-apps.herokuapp.com/data/network.sql
  - wget http://todi-apps.herokuapp.com/data/routable_network.sql
  - psql -U postgres -d isochrones_test < catchment.sql
  - psql -U postgres -d isochrones_test < network.sql

install:
  - sudo apt-get install python-software-properties -y
  - sudo sh -c "echo 'deb https://qgis.org/debian bionic main' >> /tmp/qgis.list"
  - sudo cp /tmp/qgis.list /etc/apt/sources.list.d/
  - rm /tmp/qgis.list
  - wget -O - https://qgis.org/downloads/qgis-2017.gpg.key | gpg --import
  - gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -
  - sudo apt-get update -y
  - sudo apt-get install qgis python-qgis qgis-plugin-grass -y
  - sudo apt-get install -y git xvfb python-nose python-coverage pyflakes python-nosexcover
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade pylint

before_script:
    - echo "Build starting on `date`"
    - export QGIS_PREFIX_PATH=/usr
    - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
    - echo "PYTHONPATH " $PYTHONPATH
    - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib


script:
   - make pep8
   - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=iso iso

notifications:
  email:
    - smwltwesa6@gmail.com
