services:
    - docker

env:
  global:
    - ON_TRAVIS=true
    - MUTE_LOGS=true
    - WITH_PYTHON_PEP=true
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_VERSION_TAG=latest
    - QGIS_VERSION_TAG=release-3_4

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

branches:
  only:
    - master
    - develop
    - experimental

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade flake8
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e WITH_PYTHON_PEP=${WITH_PYTHON_PEP} -e ON_TRAVIS=${ON_TRAVIS} -e MUTE_LOGS=${MUTE_LOGS} -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh isochrones"

  # FIX default installation because the sources must be in "inasafe" parent folder
  - docker exec -it qgis-testing-environment sh -c "rm -f  /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/isochrones"
  - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory/ /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/isochrones"

script:
  # The real test
  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test"
  - make pep8

notifications:
  email:
    - smwltwesa6@gmail.com
