language: python
sudo: required
dist: trusty

python:
    - 2.7

virtualenv:
    # Make apt installed Python packages work (i.e. PyQt) because Travis runs
    # tests in a virtualenv for Python 2.7.
    system_site_packages: true

services:
    - postgresql

before_install:
  - sudo apt-get -qq -y update

install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y git qgis python-qgis xvfb python-nose python-coverage pyflakes python-nosexcover
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade pylint

before_script:
    - echo "Build starting on `date`"
    - wget http://todi-apps.herokuapp.com/data/catchment.sql
    - wget http://todi-apps.herokuapp.com/data/network.sql
    - psql -c 'create database isochrones_test;' -U postgres
    - psql -c 'create extension postgis;' -U postgres
    - psql -U postgres -d iso < catchment.sql
    - psql -U postgres -d iso < network.sql


script:
   - make pep8
   - - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=iso iso


email: 
    -smwakisambwe@worldbank.org
    -smwltwesa6@gmail.com
